//############################################################################################################################
//BookCheckInPage: Used to check in a book
//On basis of card number, book id or borrowers fname or lname we can find if any checkedout book is there if yes we can 
//return that book
//############################################################################################################################

package librarymanagementsystem;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static librarymanagementsystem.ImportData.conn;

/**
 *
 * @author swetalina
 */
public class BookCheckInPage extends javax.swing.JFrame {
    private Object stmt;

    /**
     * Creates new form BookCheckInPage
     */
    public BookCheckInPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBookID = new javax.swing.JTextField();
        jcardno = new javax.swing.JTextField();
        jfname = new javax.swing.JTextField();
        jlname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        op_table = new javax.swing.JTable();
        jCheckIN = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("DETAILS TO CHECK IN BOOK:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/pictures/CHECK IN.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("BOOK ID: ");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("CARD NUMBER:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText(" FIRST NAME:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText(" LAST NAME: ");

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("BORROWERS DETAILS :");

        jBack.setText("BACK");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        op_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "LOAN_ID", "BOOK_ID", "BRANCH_ID", "CARD_NO", "DATE_OUT", "DUE_DATE", "DATE_IN"
            }
        ));
        op_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(op_table);

        jCheckIN.setText("CHECKIN");
        jCheckIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlname, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jfname)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcardno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButton1))
                    .addComponent(jLabel7))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(151, 151, 151))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCheckIN)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jBack))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcardno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckIN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", "");
         Statement stmt = conn.createStatement();
         stmt.execute("use library;");
         
          
         if(jBookID.getText().equals("")&& jcardno.getText().equals("")&& jfname.getText().equals("")&& jlname.getText().equals(""))
             JOptionPane.showMessageDialog(null, "Please enter some values");
         
         else{
              for(int k=0;k<i;k++){
                op_table.setValueAt(" ", k, 0);
                op_table.setValueAt(" ", k, 1);
                op_table.setValueAt(" ", k, 2);
                op_table.setValueAt(" ", k, 3);
                op_table.setValueAt(" ", k, 4);
                op_table.setValueAt(" ", k, 5);
                op_table.setValueAt(" ", k, 6);
              }
             i=0;
          
             String book_ID=jBookID.getText();
             String card_No=jcardno.getText();
             String fName=jfname.getText();
             String lName=jlname.getText();  
           
             if(!jBookID.getText().equals("")&& !jcardno.getText().equals("")){
             rs=stmt.executeQuery("SELECT * FROM BOOK_LOANS natural join "
                     + "(Select Card_no from borrower where fname like '%"+fName+"%' "
                     + "and lname like '%"+lName+"%' group by Card_no ) as B WHERE B.Card_no=card_no "
                     + "and book_id= '"+book_ID+"' and card_no= '"+card_No+"' and Date_in='NULL';");}
             
             else if(jBookID.getText().equals("")&& !jcardno.getText().equals(""))
             {
                 rs=stmt.executeQuery("SELECT * FROM BOOK_LOANS natural join "
                     + "(Select Card_no from borrower where fname like '%"+fName+"%' "
                     + "and lname like '%"+lName+"%' group by Card_no ) as B WHERE B.Card_no=card_no "
                     + "and card_no= '"+card_No+"' and Date_in='NULL';"); 
             }
             else if(!jBookID.getText().equals("")&& jcardno.getText().equals(""))
             {
                 rs=stmt.executeQuery("SELECT * FROM BOOK_LOANS natural join "
                     + "(Select Card_no from borrower where fname like '%"+fName+"%' "
                     + "and lname like '%"+lName+"%' group by Card_no ) as B WHERE B.Card_no=card_no "
                     + "and book_id= '"+book_ID+"' and  Date_in='NULL';"); 
             }
             
             else if(jBookID.getText().equals("")&& jcardno.getText().equals("") &&(!jfname.getText().equals("")|| !jlname.getText().equals("")))
             {
                 rs=stmt.executeQuery("SELECT * FROM BOOK_LOANS natural join "
                     + "(Select Card_no from borrower where fname like '%"+fName+"%' "
                     + "and lname like '%"+lName+"%' group by Card_no ) as B WHERE B.Card_no=card_no "
                     + "and  Date_in='NULL';"); 
             }
             while (rs.next())
             {
                 int tableloanId=rs.getInt("Loan_id");
                 String tablebookId=rs.getString("Book_id");
                 int tablebranchid=rs.getInt("Branch_id");
                 int tablecardno=rs.getInt("Card_no");
                 String tabledateOut=rs.getString("Date_out");
                 String tabledueDate=rs.getString("Due_Date");
                 String tabledateIn=rs.getString("Date_in");     
                 
                op_table.setValueAt(tableloanId, i, 0);
                op_table.setValueAt(tablebookId, i, 1);
                op_table.setValueAt(tablebranchid, i, 2);
                op_table.setValueAt(tablecardno, i, 3);
                op_table.setValueAt(tabledateOut, i, 4);
                op_table.setValueAt(tabledueDate, i, 5);
                op_table.setValueAt(tabledateIn, i, 6);
                i++;     
             }   
         if(i==0)
         JOptionPane.showMessageDialog(null, "No match found");   
         
         conn.close();   
         }
        }
         catch(SQLException ex){
        System.out.println("Error in connection: " + ex.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
         this.setVisible(false); 
        WelcomePage wp= new WelcomePage();
         wp.setVisible(true);
         
    }//GEN-LAST:event_jBackActionPerformed

    private void op_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op_tableMouseClicked

    }//GEN-LAST:event_op_tableMouseClicked

    private void jCheckINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckINActionPerformed
  
         try{
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", "");
         Statement stmt = conn.createStatement();
         stmt.execute("use library;"); 
        int row=op_table.getSelectedRow();
                int loanid = (int)op_table.getValueAt(row,0);
//                String bookid=(String)op_table.getValueAt(row, 1);
//                int branchid=(int)op_table.getValueAt( row, 2);
//                int cardno=(int)op_table.getValueAt(row, 3);
                String dain=(String)op_table.getValueAt(row, 6); 
                DateFormat dateformat= new SimpleDateFormat("yyyy-MM-dd");//Format defining
                Date date=new Date();//current date
                String datein=dateformat.format(date);
                JOptionPane.showMessageDialog(null, "Are you sure you want to Checkin");
                
                
                if (dain.equals("NULL"))
                {    
                stmt.executeUpdate("UPDATE BOOK_LOANS SET Date_in='"+datein+"' WHERE Loan_id= '"+loanid+"';");
                 for(int k=0;k<i;k++){
                op_table.setValueAt("", k, 0);
                op_table.setValueAt("", k, 1);
                op_table.setValueAt("", k, 2);
                op_table.setValueAt("", k, 3);
                op_table.setValueAt("", k, 4);
                op_table.setValueAt("", k, 5);
                op_table.setValueAt("", k, 6);
              }
             i=0;
                 JOptionPane.showMessageDialog(null,"Check In suceessful!!"); 
                }   
         }
            catch(SQLException ex){
        System.out.println("Error in connection: " + ex.getMessage());}
         
    }//GEN-LAST:event_jCheckINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookCheckInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookCheckInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookCheckInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookCheckInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookCheckInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JTextField jBookID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCheckIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jcardno;
    private javax.swing.JTextField jfname;
    private javax.swing.JTextField jlname;
    private javax.swing.JTable op_table;
    // End of variables declaration//GEN-END:variables
int i;
ResultSet rs;
}
